\restrict dbmate

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: Cloze; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "Cloze";


--
-- Name: Lesson; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "Lesson";


--
-- Name: Verb; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "Verb";


--
-- Name: GetVerbExercise(integer); Type: FUNCTION; Schema: Lesson; Owner: -
--

CREATE FUNCTION "Lesson"."GetVerbExercise"(par_lesson integer) RETURNS jsonb
    LANGUAGE sql
    AS $$
SELECT jsonb_agg(
    jsonb_build_object(
        'id', le.id,
        'type', ve.type,
        'title', ve.title,
        'description', ve.description,
        'infinitive', vb.infinitive,
        'forms', jsonb_build_object(
            'p1ev', vb.p1ev,
            'p2ev', vb.p2ev,
            'p3ev', vb.p3ev,
            'p1mv', vb.p1mv,
            'p2mv', vb.p2mv,
            'p3mv', vb.p3mv
        )
    )
)
FROM "Lesson"."Exercises" le
JOIN "Verb"."Exercises" ve
    ON ve.id = le."exerciseId"
JOIN "Verb"."Verbs" vb
    ON vb.id = ve."verbId"
WHERE le."exerciseType" = 'verb'
  AND le."lessonId" = par_lesson;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Exercises; Type: TABLE; Schema: Cloze; Owner: -
--

CREATE TABLE "Cloze"."Exercises" (
    id integer NOT NULL,
    created_at time without time zone DEFAULT now() NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    description text NOT NULL
);


--
-- Name: Exercises_id_seq; Type: SEQUENCE; Schema: Cloze; Owner: -
--

ALTER TABLE "Cloze"."Exercises" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Cloze"."Exercises_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Gaps; Type: TABLE; Schema: Cloze; Owner: -
--

CREATE TABLE "Cloze"."Gaps" (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    "sentenceId" integer NOT NULL,
    "position" smallint NOT NULL,
    correct text NOT NULL,
    hint character varying(50) NOT NULL,
    alt text[] NOT NULL
);


--
-- Name: Gaps_id_seq; Type: SEQUENCE; Schema: Cloze; Owner: -
--

ALTER TABLE "Cloze"."Gaps" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Cloze"."Gaps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sentences; Type: TABLE; Schema: Cloze; Owner: -
--

CREATE TABLE "Cloze"."Sentences" (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    textparts text[] NOT NULL
);


--
-- Name: Sentences_id_seq; Type: SEQUENCE; Schema: Cloze; Owner: -
--

ALTER TABLE "Cloze"."Sentences" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Cloze"."Sentences_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Exercises; Type: TABLE; Schema: Lesson; Owner: -
--

CREATE TABLE "Lesson"."Exercises" (
    id integer NOT NULL,
    created_at time without time zone DEFAULT now() NOT NULL,
    "lessonId" integer NOT NULL,
    "seqNumber" integer NOT NULL,
    "exerciseType" text NOT NULL,
    "exerciseId" integer NOT NULL
);


--
-- Name: Exercises_id_seq; Type: SEQUENCE; Schema: Lesson; Owner: -
--

ALTER TABLE "Lesson"."Exercises" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Lesson"."Exercises_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lessons; Type: TABLE; Schema: Lesson; Owner: -
--

CREATE TABLE "Lesson"."Lessons" (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    type character varying(25),
    level character varying(3),
    title character varying(255),
    description text,
    image text[]
);


--
-- Name: Lessons_id_seq; Type: SEQUENCE; Schema: Lesson; Owner: -
--

ALTER TABLE "Lesson"."Lessons" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Lesson"."Lessons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Exercises; Type: TABLE; Schema: Verb; Owner: -
--

CREATE TABLE "Verb"."Exercises" (
    id integer NOT NULL,
    type text NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    "verbId" integer NOT NULL
);


--
-- Name: Exercises_id_seq; Type: SEQUENCE; Schema: Verb; Owner: -
--

ALTER TABLE "Verb"."Exercises" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Verb"."Exercises_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Verbs; Type: TABLE; Schema: Verb; Owner: -
--

CREATE TABLE "Verb"."Verbs" (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    infinitive character varying(255) NOT NULL,
    tense smallint NOT NULL,
    p1ev character varying(255) NOT NULL,
    p2ev character varying(255) NOT NULL,
    p3ev character varying(255) NOT NULL,
    p1mv character varying(255) NOT NULL,
    p2mv character varying(255) NOT NULL,
    p3mv character varying(255) NOT NULL
);


--
-- Name: Verbs_id_seq; Type: SEQUENCE; Schema: Verb; Owner: -
--

ALTER TABLE "Verb"."Verbs" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Verb"."Verbs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: Exercises Exercises_pkey; Type: CONSTRAINT; Schema: Cloze; Owner: -
--

ALTER TABLE ONLY "Cloze"."Exercises"
    ADD CONSTRAINT "Exercises_pkey" PRIMARY KEY (id);


--
-- Name: Gaps Gaps_pkey; Type: CONSTRAINT; Schema: Cloze; Owner: -
--

ALTER TABLE ONLY "Cloze"."Gaps"
    ADD CONSTRAINT "Gaps_pkey" PRIMARY KEY (id);


--
-- Name: Sentences Sentences_pkey; Type: CONSTRAINT; Schema: Cloze; Owner: -
--

ALTER TABLE ONLY "Cloze"."Sentences"
    ADD CONSTRAINT "Sentences_pkey" PRIMARY KEY (id);


--
-- Name: Exercises exercises_pk; Type: CONSTRAINT; Schema: Lesson; Owner: -
--

ALTER TABLE ONLY "Lesson"."Exercises"
    ADD CONSTRAINT exercises_pk PRIMARY KEY (id);


--
-- Name: Lessons lessons_index; Type: CONSTRAINT; Schema: Lesson; Owner: -
--

ALTER TABLE ONLY "Lesson"."Lessons"
    ADD CONSTRAINT lessons_index UNIQUE (type, level, title);


--
-- Name: Lessons lessons_pk; Type: CONSTRAINT; Schema: Lesson; Owner: -
--

ALTER TABLE ONLY "Lesson"."Lessons"
    ADD CONSTRAINT lessons_pk PRIMARY KEY (id);


--
-- Name: Exercises Exercises_pkey; Type: CONSTRAINT; Schema: Verb; Owner: -
--

ALTER TABLE ONLY "Verb"."Exercises"
    ADD CONSTRAINT "Exercises_pkey" PRIMARY KEY (id);


--
-- Name: Verbs verbs_pkey; Type: CONSTRAINT; Schema: Verb; Owner: -
--

ALTER TABLE ONLY "Verb"."Verbs"
    ADD CONSTRAINT verbs_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: verbs_index; Type: INDEX; Schema: Verb; Owner: -
--

CREATE UNIQUE INDEX verbs_index ON "Verb"."Verbs" USING btree (infinitive, tense);


--
-- Name: Gaps Gaps_Sentence; Type: FK CONSTRAINT; Schema: Cloze; Owner: -
--

ALTER TABLE ONLY "Cloze"."Gaps"
    ADD CONSTRAINT "Gaps_Sentence" FOREIGN KEY ("sentenceId") REFERENCES "Cloze"."Sentences"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: Exercises exercises_lesson; Type: FK CONSTRAINT; Schema: Lesson; Owner: -
--

ALTER TABLE ONLY "Lesson"."Exercises"
    ADD CONSTRAINT exercises_lesson FOREIGN KEY ("lessonId") REFERENCES "Lesson"."Lessons"(id);


--
-- Name: Exercises verbexercise_verb; Type: FK CONSTRAINT; Schema: Verb; Owner: -
--

ALTER TABLE ONLY "Verb"."Exercises"
    ADD CONSTRAINT verbexercise_verb FOREIGN KEY ("verbId") REFERENCES "Verb"."Verbs"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict dbmate


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20260706082500'),
    ('20260706090400'),
    ('20260706105300'),
    ('20260706111628'),
    ('20260706180613'),
    ('20260706181146'),
    ('20260706181337'),
    ('20260706181731'),
    ('20260706182242'),
    ('20260706182455'),
    ('20260706193802'),
    ('20260706194859'),
    ('20260706195716'),
    ('20260706200016'),
    ('20260706201708'),
    ('20260706202650'),
    ('20260710082907');
