-- migrate:up
CREATE TABLE IF NOT EXISTS "Card"."Exercises"
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    image text[] COLLATE pg_catalog."default",
    "deckId" integer NOT NULL,
    CONSTRAINT "Exercises_pkey" PRIMARY KEY (id),
    CONSTRAINT "Exercise_deck" FOREIGN KEY ("deckId")
        REFERENCES "Card"."Decks" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Card"."Exercises"
    OWNER to docent;
    
-- migrate:down
DROP TABLE IF EXISTS "Cards"."Exercises";

