-- migrate:up

-- Cloze.SentenceSets
CREATE TABLE IF NOT EXISTS "Cloze"."SentenceSets"
(
   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "SentenceSets_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS "Cloze"."SentenceSets"
    OWNER to docent;

INSERT INTO "Cloze"."SentenceSets" ("id", "title")
SELECT "id", "title"
FROM "Cloze"."Exercises"
WHERE "id" < 10;

SELECT setval(
    pg_get_serial_sequence('"Cloze"."SentenceSets"', 'id'),
    COALESCE((SELECT MAX("id") FROM "Cloze"."SentenceSets"), 1),
    true
);

-- Cloze.Exercises
ALTER TABLE "Cloze"."Exercises"
    ADD COLUMN "sentenceSetId" integer;

UPDATE "Cloze"."Exercises"
SET "sentenceSetId" = "id"
WHERE "id" < 10;

ALTER TABLE "Cloze"."Exercises"
    ADD CONSTRAINT "Exercises_sentenceSetId_fkey"
    FOREIGN KEY ("sentenceSetId")
    REFERENCES "Cloze"."SentenceSets" ("id");

-- Cloze.Sentences
ALTER TABLE "Cloze"."Sentences"
    DROP CONSTRAINT IF EXISTS "Sentences_exerciseId_fkey";

ALTER TABLE "Cloze"."Sentences"
    RENAME COLUMN "exerciseId" TO "sentenceSetId";

ALTER TABLE "Cloze"."Sentences"
    ADD CONSTRAINT "Sentences_sentenceSetId_fkey"
    FOREIGN KEY ("sentenceSetId")
    REFERENCES "Cloze"."SentenceSets" ("id");

-- migrate:down

-- Cloze.Exercises
ALTER TABLE "Cloze"."Exercises"
    DROP CONSTRAINT IF EXISTS "Exercises_sentenceSetId_fkey";

ALTER TABLE "Cloze"."Exercises"
    DROP COLUMN IF EXISTS "sentenceSetId";

-- Cloze.Sentences
ALTER TABLE "Cloze"."Sentences"
    DROP CONSTRAINT IF EXISTS "Sentences_sentenceSetId_fkey";

ALTER TABLE "Cloze"."Sentences"
    RENAME COLUMN "sentenceSetId" TO "exerciseId";

ALTER TABLE "Cloze"."Sentences"
    ADD CONSTRAINT "Sentences_exerciseId_fkey"
    FOREIGN KEY ("exerciseId")
    REFERENCES "Cloze"."Exercises" ("id");

-- Cloze.SentenceSets
DROP TABLE "Cloze"."SentenceSets";


