-- migrate:up
CREATE TABLE IF NOT EXISTS "Chat"."Exercises"
(
   id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type character varying COLLATE pg_catalog."default" NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    image text[] COLLATE pg_catalog."default",
    introduction text COLLATE pg_catalog."default",
    prompt text COLLATE pg_catalog."default",
    words character varying[] COLLATE pg_catalog."default",
    avatar jsonb,
    voice jsonb,
    CONSTRAINT "Exercises_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Chat"."Exercises"
    OWNER to docent;

-- migrate:down
DROP TABLE "Chat"."Exercises"
