-- migrate:up
CREATE TABLE IF NOT EXISTS "Card"."Cards"
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    text character varying(255) COLLATE pg_catalog."default" NOT NULL,
    image text[] COLLATE pg_catalog."default",
    CONSTRAINT "Card_pkey" PRIMARY KEY (id),
    CONSTRAINT Card_unique UNIQUE (text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Card"."Cards"
    OWNER to docent;

-- migrate:down
DROP TABLE IF EXISTS "Card"."Cards";
