-- migrate:up
CREATE TABLE IF NOT EXISTS "Lesson"."Exercises"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at time without time zone NOT NULL DEFAULT now(),
    "lessonId" integer NOT NULL,
    "seqNumber" integer NOT NULL,
    "exerciseType" text COLLATE pg_catalog."default" NOT NULL,
    "exerciseId" integer NOT NULL,
    CONSTRAINT exercises_pk PRIMARY KEY (id),
    CONSTRAINT exercises_lesson FOREIGN KEY ("lessonId")
        REFERENCES "Lesson"."Lessons" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Lesson"."Exercises"
    OWNER to docent;

-- migrate:down
DROP TABLE IF EXISTS "Lesson"."Exercises";