-- migrate:up
CREATE TABLE IF NOT EXISTS "Verb"."Exercises"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    "verbId" integer NOT NULL,
    CONSTRAINT "Exercises_pkey" PRIMARY KEY (id),
    CONSTRAINT verbexercise_verb FOREIGN KEY ("verbId")
        REFERENCES "Verb"."Verbs" (id) MATCH SIMPLE
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Verb"."Exercises"
    OWNER to docent;

-- migrate:down
DROP TABLE IF EXISTS "Verb"."Exercises";

