-- migrate:up
CREATE TABLE IF NOT EXISTS "Babel"."Translations"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    "tableName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "keyId" integer NOT NULL,
    language character varying(3) COLLATE pg_catalog."default" NOT NULL,
    text text COLLATE pg_catalog."default",
    CONSTRAINT "Translation_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Babel"."Translations"
    OWNER to docent;

CREATE UNIQUE INDEX IF NOT EXISTS "Translations_RefId"
    ON "Babel"."Translations" USING btree
    ("tableName" COLLATE pg_catalog."default" ASC NULLS LAST, "keyId" ASC NULLS LAST, language COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-- migrate:down
DROP TABLE IF EXISTS "Babel"."Translations";
