-- migrate:up
CREATE TABLE IF NOT EXISTS "Verb"."Verbs"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    infinitive character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tense smallint NOT NULL,
    p1ev character varying(255) COLLATE pg_catalog."default" NOT NULL,
    p2ev character varying(255) COLLATE pg_catalog."default" NOT NULL,
    p3ev character varying(255) COLLATE pg_catalog."default" NOT NULL,
    p1mv character varying(255) COLLATE pg_catalog."default" NOT NULL,
    p2mv character varying(255) COLLATE pg_catalog."default" NOT NULL,
    p3mv character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT verbs_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Verb"."Verbs"
    OWNER to docent;

CREATE UNIQUE INDEX IF NOT EXISTS verbs_index
    ON "Verb"."Verbs" USING btree
    (infinitive COLLATE pg_catalog."default" ASC NULLS LAST, tense ASC NULLS LAST)
    TABLESPACE pg_default;

-- migrate:down
DROP TABLE IF EXISTS "Verb"."Verbs";
