-- migrate:up
CREATE TABLE IF NOT EXISTS "Cloze"."Gaps"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    "sentenceId" integer NOT NULL,
    "position" smallint NOT NULL,
    correct text COLLATE pg_catalog."default" NOT NULL,
    hint character varying(50) COLLATE pg_catalog."default" NOT NULL,
    alt text[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Gaps_pkey" PRIMARY KEY (id),
    CONSTRAINT "Gaps_Sentence" FOREIGN KEY ("sentenceId")
        REFERENCES "Cloze"."Sentences" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Cloze"."Gaps"
    OWNER to docent;

-- migrate:down
DROP TABLE IF EXISTS "Cloze".Gaps;

