-- migrate:up
CREATE TABLE IF NOT EXISTS "Lesson"."Lessons"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone DEFAULT now(),
    type character varying(25) COLLATE pg_catalog."default",
    level character varying(3) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    image text[] COLLATE pg_catalog."default",
    CONSTRAINT lessons_pk PRIMARY KEY (id),
    CONSTRAINT lessons_index UNIQUE (type, level, title)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Lesson"."Lessons"
    OWNER to docent;

-- migrate:down
DROP TABLE IF EXISTS "Lesson"."Lessons";