-- migrate:up

CREATE TABLE IF NOT EXISTS "Cloze"."Exercises"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at time without time zone NOT NULL DEFAULT now(),
    type text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Exercises_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Cloze"."Exercises"
    OWNER to docent;

-- migrate:down
DROP TABLE IF EXISTS "Cloze"."Exercises";

