-- migrate:up
CREATE TABLE IF NOT EXISTS "Card"."Decks"
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    text character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "Decks_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Card"."Decks"
    OWNER to docent;
    
-- migrate:down
DROP TABLE IF EXISTS "Cards"."Exercises";
