-- migrate:up
CREATE TABLE IF NOT EXISTS "Cloze"."Sentences"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    textparts text[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Sentences_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS "Cloze"."Sentences"
    OWNER to docent;

-- migrate:down
DROP TABLE "Cloze"."Sentences";
